apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote-ns
spec:
  selector:
    app: result-deployment
  type: NodePort
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31001

